#  VERSION 1
# version: '3.1'

# services:

#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: news_feed_bot
#       PGDATA: /var/lib/postgresql/data/
#     ports:
#       - "5432:5432"
#     volumes:
#       - db:/var/lib/postgresql/data/

# volumes:
#   db:
# 
# -------------------------------------------------------------------------------------------------
#  VERSION 2
# version: '3.1'

# services:

#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: news_feed_bot
#       PGDATA: /var/lib/postgresql/data/
#     ports:
#       - "5433:5433"
#     command:
#       - "postgres"  
#       - "-c"
#       - "port=5433"
#     volumes:
#       - db:/var/lib/postgresql/data/

# volumes:
#   db:

# -------------------------------------------------------------------------------------------------
#  VERSION 3
version: '3.1'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: